# Generated by Django 4.1.2 on 2022-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Социальная жизнь', 'Социальная жизнь'), ('Учебные новости', 'Учебные новости'), ('Жизнь ВУЗа', 'Жизнь ВУЗа')], default='Социальная жизнь', max_length=32, verbose_name='Состояние заказа'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
